on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: uodate code on vps
    runs-on: self-hosted

    steps:
      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.ACCESS_KEY }}
          port: 22
          script: |
            cd /var/www/wedding_MyH
            git fetch
            git checkout main
            git pull origin main
            exit
